-- DROP TABLE TB_PARCELAS_XCAVE;
-- DROP TABLE TB_EMPRESTIMO_XCAVE;

CREATE TABLE TB_EMPRESTIMO_XCAVE(
  cd_emprestimo SERIAL PRIMARY KEY,
  nr_valor NUMERIC(6,2) NOT NULL
);

CREATE TABLE TB_PARCELAS_XCAVE(
  cd_parcela SERIAL PRIMARY KEY,
  cd_emprestimo INTEGER NOT NULL,
  nr_parcelas INTEGER NOT NULL,
  nr_valor_parcela NUMERIC(6,2) NOT NULL,
  FOREIGN KEY(cd_emprestimo) REFERENCES TB_EMPRESTIMO_XCAVE(cd_emprestimo)
);